server:
  error:
    include-stacktrace: on-param
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: spring
    password: spring
